# Workflow to build soak related containers. These trigger per-push.

name: Soak Infra

on: push

jobs:
  vector-soak:
    name: Build 'soak-vector' container (${{ matrix.target }})
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: [self-hosted, linux, x64, soak]
    strategy:
      matrix:
        target:
          - datadog_agent_remap_datadog_logs
          # - syslog_humio_logs
          # - syslog_log2metric_humio_metrics
          # - syslog_loki
          # - syslog_regex_logs2metric_ddmetrics
          # - syslog_splunk_hec_logs
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Compute image tag
        run: |
          echo "::set-output name=TAG::4f5ab2fb2f82b57a23076b9db90bcd2e335c0f0b-6a4d9d70b4479fea6e4b6b16dcfdd1048def8c34"
          # echo "::set-output name=TAG::$(soaks/bin/container_tag.sh ${{ matrix.target }} ${{ github.sha }})"
        id: image_tag

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Log in to the Container registry
      #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     flavor: |
      #       latest=false
      #       prefix=
      #       suffix=
      #     labels: |
      #       soak_test_name=${{ matrix.target }}
      #     images: ghcr.io/${{ github.repository }}/soak-vector
      #     tags: type=raw, value=${{ steps.image_tag.outputs.TAG }}

      # - name: Build and push 'soak-vector' image
      #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #   with:
      #     context: .
      #     file: soaks/Dockerfile
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      #     # cache-from: type=gha
      #     # cache-to: type=gha,mode=max
      #     build-args: |
      #       VECTOR_FEATURES=${{ steps.features.outputs.FEATURES }}

      - name: Boot the cluster
        run: |
          ./soaks/bin/boot_minikube.sh
          capture_dir=$(mktemp -d /tmp/"${SOAK_NAME}".XXXXXX)
          echo "Captures will be recorded into ${capture_dir}"
          minikube mount "${capture_dir}:/captures" &

  # observer:
  #   name: Build and push 'observer' to Github CR
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v2

  #     - name: Log in to the Container registry
  #       uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Extract metadata (tags, labels) for Docker
  #       id: meta
  #       uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
  #       with:
  #         images: ghcr.io/${{ github.repository }}/soak-observer
  #         tags: type=sha, format=long

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
  #       with:
  #         context: .
  #         file: lib/soak/Dockerfile
  #         push: true
  #         tags: ${{ steps.meta.outputs.tags }}
  #         labels: ${{ steps.meta.outputs.labels }}
