name: Soaks

on: push

jobs:
  soak:
    name: Run 'soak' (${{ matrix.target }})
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: [self-hosted, linux, x64, soak]
    strategy:
      matrix:
        target:
          - datadog_agent_remap_datadog_logs
          # - syslog_humio_logs
          # - syslog_log2metric_humio_metrics
          # - syslog_loki
          # - syslog_regex_logs2metric_ddmetrics
          # - syslog_splunk_hec_logs
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Interact with the cluster
        run: |
          minikube stop || true
          minikube delete || true
          minikube start --cpus=7 --memory=8g
