name: Soaks

on: push

jobs:
  soak:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
          - datadog_agent_remap_datadog_logs
          # - syslog_humio_logs
          # - syslog_log2metric_humio_metrics
          # - syslog_loki
          # - syslog_regex_logs2metric_ddmetrics
          # - syslog_splunk_hec_logs
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: 'v1.23.2'
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
          driver: docker
          start args: "--cpus=7 --memory=8g"
      - name: Interact with the cluster
        run: kubectl get nodes
